version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
